### ISSUE TITLE
Update registration, transfer, renewal response payload

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-developer#111]
The response of the register, transfer and renew commands was changed (to support async tasks). All the clients must be updated, and the developer referenced updated accordingly.

## Docs

- [x]  developer reference

## Clients

- [x] Elixir (dnsimple/dnsimple-elixir#88)
- [x] Go (dnsimple/dnsimple-go#52)
- [x] Node
- [x] Ruby (dnsimple/dnsimple-ruby#140)

**Comment by weppos** [comment]
@aeden is dealing with it as part of #112
