### ISSUE TITLE
Clients: Implement DNSSEC API

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-developer#143]
API documented in https://github.com/dnsimple/dnsimple-developer/pull/142

- [x] Ruby dnsimple/dnsimple-ruby#152
- [x] Go dnsimple/dnsimple-go#58
- [x] Elixir dnsimple/dnsimple-elixir#108
- [x] Node dnsimple/dnsimple-node#10
