### ISSUE TITLE
Update clients to add Email Forward changes

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-developer#315]
Add support for new payload fields, remove (or alias) deprecated fields.

See https://github.com/dnsimple/dnsimple-developer/pull/314

```[tasklist]
### Tasks
- [ ] https://github.com/dnsimple/dnsimple-ruby/pull/389
- [ ] https://github.com/dnsimple/dnsimple-java/pull/176
- [ ] https://github.com/dnsimple/dnsimple-node/pull/209
- [ ] https://github.com/dnsimple/dnsimple-go/pull/175
- [ ] https://github.com/dnsimple/dnsimple-python/pull/450
- [ ] https://github.com/dnsimple/dnsimple-elixir/pull/254
- [ ] https://github.com/dnsimple/dnsimple-php/pull/106
- [ ] https://github.com/dnsimple/dnsimple-csharp/pull/151
- [ ] https://github.com/dnsimple/dnsimple-rust/pull/57
```

**Comment by ggalmazor** [comment]
Not all clients had already deprecated the `from` and `to` fields, so the PRs I've created ensure all clients have this baseline before actually removing them.

**Comment by ggalmazor** [comment]
All tasks have been completed
